openapi: 3.0.3
info:
  title: XeniaWeb Shop API
  description: Title
  version: 1.0.0
servers:
  - url: 'http://shop-api/api/v1'
tags:
    - name: Products
      description: Products operations
    - name: Categories
      description: Categories operations
    - name: Customers
      description: Customers operations
    - name: Invoices
      description: Invoices operations

paths:
  /products:
    get:
      description: Returns all products from the system that the user has access to
      tags:
        - Products
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 144
        title:
          type: string
          example: As soon as look at a king'
        price:
          type: integer
          example: 245
        description:
          type: string
          example: And how odd the directions will lookdirections will lookdirections will lookdirections will look!. Oh dear, what nonsense I'm talking!' Just then she looked
        categoryId:
          type: integer
          example: 4
        image:
          type: string
          example: https://picsum.photos/id/1062/300/250
        comment:
          type: string
          example: just comment
  parameters:
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      required: true
      schema:
        type: integer
        format: int32
    limitParam:
      name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'



